version: "3.9"

services:
  devops-nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - ${NGINX_HTTP_EXTERNAL_PORT}:80
      - ${NGINX_HTTPS_EXTERNAL_PORT}:443
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge