version: '3.9'

services:
  database:
    image: ${DB_IMAGE_NAME}
    restart: unless-stopped
    volumes:
      - /containers/postgres:/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=tech_database
      - PGDATA=/data
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    container_name: ${DB_CONTAINER_NAME}


  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8080
    depends_on: [database]

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_EXTERNAL_PORT}:3000'
    depends_on: [backend]

  proxy:
    container_name: ${CONTROLLER_CONTAINER_NAME}
    image: ${CONTROLLER_IMAGE_NAME}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${CONTROLLER_EXTERNAL_PORT}:8080