version: "3.9"

services:
  devops-api:
    image: ${API_IMAGE_NAME}
    container_name: ${API_CONTAINER_NAME}
    depends_on: [devops-db]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${API_EXTERNAL_PORT}:8001
    restart: unless-stopped
  
  devops-db:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    environment:
      - PGDATA=/data
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nutritracker
    volumes:
      - ./containers/postgres:/data
    restart: unless-stopped