name: build | backend

on:
  pull_request:
    branches: [master]
    paths:
      - 'lab5/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab5/backend

    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/build.gradle') }}
      
      - name: build & test
        run: ./gradlew clean build test
