name: build | frontend

on:
  pull_request:
    branches: [master]
    paths:
      - "lab5/frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab5/frontend

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Test
        run: npm ci && npm run build && npm test
        continue-on-error: true