name: "deploy | nginx"

on:
  pull_request:
    branches: [master]
    paths:
      - 'lab5/nginx.conf'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nginx:mainline
  WORKDIR: lab5/

jobs:
  environment-set:
    outputs:
      branch: ${{ steps.extract-branch.outputs.branch }}
    runs-on: ubuntu-latest
    name: environment-set
    steps:

      - name: extract-branch
        shell: bash
        id: extract-branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: [ self-hosted, Linux, X64 ]
    needs: [environment-set]
    steps:

      - name: login to docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: remove previous version
        continue-on-error: true
        run: |
          docker stop nginx || true
          docker rm nginx || true
      
      - name: redeploy
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.environment-set.outputs.branch }}
          export CONTROLLER_CONTAINER_NAME=nginx
          export CONTROLLER_EXTERNAL_PORT=80
          export CONTROLLER_IMAGE_NAME=${{ env.IMAGE_NAME }}

          docker compose up -d --build --force-recreate proxy