name: "predeploy | frontend"

on:
  pull_request:
    branches: [master]
    paths:
      - "lab5/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab5/frontend

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Test
        run: |
          echo Starting build...
          START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          npm ci && npm run build && npm test

          END=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          ELAPSED=$(( $END - $START ))

          GREEN=$'\033[0;32m'
          RESET=$'\033[0m' 
          echo -e "${GREEN}Build Succeeded within ${ELAPSED}${RESET}"
        continue-on-error: true

      - name: 🕵️ show context
        run: |
          echo "Event: ${{ toJSON(github.event) }}"
          echo "Workflow: ${{ github.workflow }}"
          ls -la .github/workflows/