name: predeploy | frontend

on:
  pull_request:
    branches: [master]
    paths:
      - "lab5/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab5/frontend

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Test
        run: npm ci && npm run build && npm test
        continue-on-error: true

  dockerfile-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: execute check
        run: | 
          (ls lab5/frontend/Dockerfile >> /dev/null 2>&1 &&
            echo check completed successfully &&
            echo you are ready to go 🚀) ||
          echo 'Dockerfile' must present at lab5/frontend path && exit 1