name: predeploy-frontend

on:
  pull_request:
    branches: [master]
    paths:
      - "lab5/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab5/frontend

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Test
        run: |
          echo Starting build...
          START = $(date -u +'%Y-%m-%dT%H:%M:%SZ')

          npm ci && npm run build && npm test

          END = = $(date -u +'%Y-%m-%dT%H:%M:%SZ')
          ELAPSED = $(( $END - $START ))

          GREEN=\033[0;32m
          echo -e "${GREEN}Build Succeeded within $ELAPSED"
        continue-on-error: true

  dockerfile-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
  
      - name: execute verify
        run: |
          echo "::group::🔍 Starting Dockerfile validation"
          GREEN=\033[0;32m

          DOCKERFILE_PATH="lab5/frontend/Dockerfile"
          
          if [ ! -f "$DOCKERFILE_PATH" ]; then
            echo "::error::🚨 Dockerfile not found at: $DOCKERFILE_PATH"
            echo "::endgroup::"
            exit 1
          fi
  
          echo "✅ Dockerfile exists"
          echo "📄 File content preview:"
          head -n 5 "$DOCKERFILE_PATH"
          
          # Проверка базового образа
          if ! grep -q '^FROM' "$DOCKERFILE_PATH"; then
            echo "::error::🚫 Missing FROM instruction in Dockerfile"
            echo "::endgroup::"
            exit 1
          fi
  
          echo "🔄 Trying to build test image..."
          docker build -t test-image "$(dirname "$DOCKERFILE_PATH")"
          
          echo "::endgroup::"
          echo -e "$🎉 ${GREEN}All checks passed! You're ready to go 🚀"