name: "predeploy | backend"

on:
  pull_request:
    branches: [master]
    paths:
      - 'lab5/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab5/backend

    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/build.gradle') }}
      
      - name: build & test
        run: |
          echo Starting build...
          START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          chmod +x gradlew
          ./gradlew clean build test

          END=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          ELAPSED=$(( $END - $START ))

          GREEN=$'\033[0;32m'
          RESET=$'\033[0m' 
          echo -e "${GREEN}Build Succeeded within ${ELAPSED}${RESET}"
      
      - name: 🕵️ show context
        run: |
          echo "Event: ${{ toJSON(github.event) }}"
          echo "Workflow: ${{ github.workflow }}"
          ls -la .github/workflows/