name: "publish | frontend"

on:
  workflow_run:
    workflows: ["predeploy | frontend"]
    types: 
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}-frontend
  WORKDIR: lab5/frontend

jobs:
  check-build-status:
    runs-on: ubuntu-latest
    steps:
      - name: verify build success
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Build failed, canceling publish"
            exit 1
          fi

  publish:
    needs: check-build-status
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: extract meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
      - name: publish
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.WORKDIR }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true